id: opecha:P007848
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6525
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  volume:
    a05584f54c684f93ade80176a3f49f4e:
      image_group_id: I3CN6527
      title: Volume 1 of bod kyi gna' rabs mchims kyi rus rgyud skor brjod pa/
      volume_number: 1
      total_pages: 214
  author: ''
ebook_metadata:
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  sku: P007848
  cover: cover.jpg
  layers:
  - pagination
