id: P007848
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6525
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  volumes:
    2588406745984c4db24cdd6d7b795d2c:
      image_group_id: I3CN6527
      title: ''
      volume_number: 1
      total_pages: 214
ebook_metadata:
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  sku: P007848
  cover: cover.jpg
  layers:
  - pagination
